using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using Toggl_Reports.Models;
using Toggl_Reports.Services;

namespace Toggl_Reports
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            var service = new TogglTimeEntriesService();
            var viewModel = new ViewModels.MainViewModel(service, this);
            this.DataContext = viewModel;
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var dataGrid = sender as DataGrid;
            var data = dataGrid.ItemsSource
                .Cast<object>()
                .FirstOrDefault() as DateCollection[];
            if (data == null) return;
            dataGrid.Columns.Clear();
            dataGrid.Columns.Add(new DataGridTextColumn { Header = "WorkspaceName", Binding = new Binding("WorkspaceName") });
            dataGrid.Columns.Add(new DataGridTextColumn { Header = "ClientName", Binding = new Binding("ClientName") });
            dataGrid.Columns.Add(new DataGridTextColumn { Header = "ProjectName", Binding = new Binding("ProjectName") });
            dataGrid.Columns.Add(new DataGridTextColumn { Header = "Description", Binding = new Binding("Description") });
            foreach (var date in data.Select(i => i.Date).ToArray())
            {
                dataGrid.Columns.Add(new DataGridTextColumn { Header = date, Binding = new Binding(date.ToShortDateString()) });
            }
        }

        private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {

        }
    }
}
